services:
  model_auth_switch:
    image: ghcr.io/luler/model_auth_switch:latest
    restart: always
    ports:
      - 20261:3000
    volumes:
      - ./runtime:/app/runtime
    environment:
      - TZ=${TZ:-Asia/Shanghai}                         #时区
      - PORT=${PORT:-3000}                              #服务端口
      #数据库配置
      - DATABASE_DEFAULT_DRIVER=${DATABASE_DEFAULT_DRIVER:-sqlite}
      - DATABASE_DEFAULT_NAME=${DATABASE_DEFAULT_NAME:-runtime/model_auth_switch.sqlite}
      #SMTP邮件配置
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-your_email@example.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-your_password}
      - SMTP_FROM=${SMTP_FROM:-your_email@example.com}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-EmailTool}
