services:
  model_auth_switch:
    image: ghcr.io/luler/model_auth_switch:latest
    restart: always
    ports:
      - 20261:3000
    volumes:
      - ./runtime:/app/runtime
      - ./app/appconfig/openai_proxy.yaml:/app/app/appconfig/openai_proxy.yaml
    environment:
      - TZ=${TZ:-Asia/Shanghai}                         #时区
      - PORT=${PORT:-3000}                              #服务端口
